#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-AU-TFN
version:      0.1
version_from: lib/Business/AU/TFN.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
